debug: true
build:
  image: node
  commands:
    - npm install --development
    - npm test
publish:
  ecr:
    access_key: $$ECR_ACCESS_KEY
    secret_key: $$ECR_SECRET_KEY
    region: eu-central-1
    repo: 711655675495.dkr.ecr.eu-central-1.amazonaws.com/drone-lab
    tag: latest
    file: Dockerfile

deploy:
  ecs:
    image: plugins/drone-ecs
    region: eu-central-1
    cluster: drone-test
    access_key: $$ECR_ACCESS_KEY
    secret_key: $$ECR_SECRET_KEY
    family: drone-test-family
    image_name: 711655675495.dkr.ecr.eu-central-1.amazonaws.com/drone-lab
    image_tag: latest
    service: drone-test-service
    port_mappings:
      - 3000 3000
    memory: 128
