
build:
  image: node
  commands:
    - npm install --development
    - npm test
pipeline:
  ssh:
    image: plugins/ssh
    host: localhost
    user: ubuntu
    key: $$SSH_PRIVATE_KEY
    port: 22
    script:
      - echo hello
      - echo world
