debug: true
build:
  image: node
  commands:
    - npm install --development
    - npm test
publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    image: dagonzadub/drone-selfsigned-docker
    #email: $$DOCKER_EMAIL
    registry: 35.156.218.164
    repo: node-example
    tag: latest
    insecure: true
