
build:
  image: node
  commands:
    - npm install --development
    - npm test
    - echo Hello $$ECR_ACCESS_KEY
publish:
  ecr:
    repo: 711655675495.dkr.ecr.eu-central-1.amazonaws.com/drone-lab
    region: eu-central-1
    tag: latest
    file: Dockerfile
    access_key: $$ECR_ACCESS_KEY
    secret_key: $$ECR_SECRET_KEY
