debug: true
build:
  image: node
  commands:
    - npm install --development
    - npm test
publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    image: dagonzadub/drone-selfsigned-docker
    #email: $$DOCKER_EMAIL
    repo: 35.156.218.164:5000/node-test
    tag: latest
    insecure: true
