debug: true
build:
  image: node
  commands:
    - npm install --development
    - npm test
publish:
  ecr:
    access_key: $$ECR_ACCESS_KEY
    secret_key: $$ECR_SECRET_KEY
    region: eu-central-1
    repo: 711655675495.dkr.ecr.eu-central-1.amazonaws.com/drone-lab
    tag: latest
    file: Dockerfile

deploy:
  ssh:
    host: 35.156.208.125
    user: ubuntu
    port: 22
    commands:
      - git -C /apps/node-example-drone pull origin master
      - pm2 delete all
      - pm2 start /apps/node-example-drone/index.js
